services:
  postgres:
    image: postgres:17.4-alpine
    container_name: my_postgres
    restart: always
    environment:
      POSTGRES_DB: swift_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secretpassword
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/migration/000001_migration_name.up.sql:/docker-entrypoint-initdb.d/init.sql

  swift_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: swift_service
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  pgdata:
    driver: local