// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

type SwiftDatum struct {
	ID              int32  `json:"id"`
	CountryIso2Code string `json:"country_iso2_code"`
	SwiftCode       string `json:"swift_code"`
	CodeType        string `json:"code_type"`
	BankName        string `json:"bank_name"`
	Address         string `json:"address"`
	TownName        string `json:"town_name"`
	CountryName     string `json:"country_name"`
	TimeZone        string `json:"time_zone"`
}
