// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"context"
)

type Querier interface {
	AddNewSwiftCode(ctx context.Context, arg AddNewSwiftCodeParams) (SwiftDatum, error)
	CreateSwiftData(ctx context.Context, arg CreateSwiftDataParams) error
	DeleteSwiftCode(ctx context.Context, swiftCode string) (SwiftDatum, error)
	GetDetailsCountry(ctx context.Context, countryIso2Code string) ([]GetDetailsCountryRow, error)
	GetDetailsSwift(ctx context.Context, swiftCode string) ([]GetDetailsSwiftRow, error)
}

var _ Querier = (*Queries)(nil)
