// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: swift.sql

package db

import (
	"context"
)

const createSwiftData = `-- name: CreateSwiftData :exec
INSERT INTO swift_data (
    country_iso2_code,
    swift_code,
    code_type,
    bank_name,
    address,
    town_name,
    country_name,
    time_zone
) 
VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
`

type CreateSwiftDataParams struct {
	CountryIso2Code string `json:"country_iso2_code"`
	SwiftCode       string `json:"swift_code"`
	CodeType        string `json:"code_type"`
	BankName        string `json:"bank_name"`
	Address         string `json:"address"`
	TownName        string `json:"town_name"`
	CountryName     string `json:"country_name"`
	TimeZone        string `json:"time_zone"`
}

func (q *Queries) CreateSwiftData(ctx context.Context, arg CreateSwiftDataParams) error {
	_, err := q.db.ExecContext(ctx, createSwiftData,
		arg.CountryIso2Code,
		arg.SwiftCode,
		arg.CodeType,
		arg.BankName,
		arg.Address,
		arg.TownName,
		arg.CountryName,
		arg.TimeZone,
	)
	return err
}
